---
title: "Homepage"
format: html
editor: visual
---

### About Me

I am Yutong Li, an undergraduate student in Applied Mathematics at Xi'an Jiaotong-Liverpool University.
I am interested in applied problems in statistics, such as bio-statistics and public health related data.


### Activity

	(1) Fertility and Beauty Consumption: 
	Built a CFPS panel (2012–2022) and applied a Difference-in-Differences (DID) with Two-Stage Least Squares (2SLS) framework. 
	Findings show the universal two-child policy significantly increased fertility among targeted women, while higher fertility reduced beauty expenditures.
	
	(2) Interaction of PM2.5 and Waist-to-Hip Ratio on Brain Structure: 
	Analyzed 39,171 neuroimaging and epidemiological samples, finding that low-level PM2.5 and WHR jointly affect subcortical and cortical brain regions, with stronger effects in females. 
	Results suggest certain brain areas are more vulnerable to combined environmental and metabolic factors.
	
	(3) Survival Analysis in Pesticide Poisoning Patients: 
	Applied Cox-Lasso and backward Cox regression to identify CPR, intubation or ventilation, vasopressors, age, and ingested dose as key predictors of survival,
	providing practical evidence for treatment optimization.
	
Beyond research, I have delivered talks at the Workshop on Exploring Mathematics with AI and participated in a public health statistics summer camp. 

I am skilled in R, MATLAB, and Java.



